### ISSUE TITLE
Missing features

### ISSUE THREAD

**Issue by jonnyynnoj** [PhpUnitsOfMeasure/php-units-of-measure#35]
Just started using this but having some issues with features that aren't implemented compared to the front end library I'm using (js-quantities)
1. **No multiplication/division**
   js-quantities allows you to multiply a quantity by a numeric factor or another quantity.
2. **toUnit method doesn't return new quantity**
   Currently the toUnit method will return the converted quantity as a float rather than a new quantity instance. This feels inconsistent with how adding/subtracting quantities works; if you want to perform further operations you have to manually create the new quantity like so `new Length($qty->toUnit('ft'), 'ft')`
3. **No methods to access scalar and unit values**
   Basically just needs something like `scalar()` and `unit()` methods that will return `originalValue` and `originalUnit` respectively.
4. **Can't create generic quantities**
   For example, from user supplied inputs of either a mass or volume measurement it's not possible to create a quantity without checking what type of unit the measurement is. You can't do `new Quantity($scalar, $unit)` instead you have to check if its a mass or volume then create the class

```
$type = isLiquid($unit) ? 'Mass' : 'Volume';
$qty = new $type($scalar, $unit)
```

I hope these are valid suggestions. At the moment I've patched/added 1, 2, & 3, would they be worth sending in a PR? Maybe the change to `toUnit` would be better as a separate method for backwards compatibility?

**Comment by triplepoint** [comment]
Hello, and thanks for your interest!  Let me reply to your points in order:

1. I'm currently working on a branch that supports multiplication and division of quantities.  This is tricky, because unlike other possible implementations, I'm trying to use types to represent different physical quantities.  So for instance a Length object is a different type from a Mass object.  While addition and subtraction can easily be limited to only operate on similar types (Length + Length, for example), multiplication and division can operate on differing types to produce new types (Distance / Time = Velocity).  Getting this right has been slow going, but its my hope that when complete I can do away with all but the basic physical quantities, and get derived quantities like Velocity and Area (and compound units like meters/year and miles^2) for free.  I'd be curious to see what you came up for this.

2.  I can go along with this.  The interface would seem more logical if toUnit() returned a new PhysicalQuantity, and there were some other method (like your scalar() suggestion) to extract a unit value.  This would match the immutable intent a bit better.  I'll keep this one in mind for a future release.

3. Agreed, as part of the change suggested in 2.

4. This is fallout of not having a single Quantity() type.  I can see the argument for doing things the way js-quantities did it, but I chose not to go that way and instead favored more precise types.  It might be possible to clean up your example with some helper methods into something more like:
``` php
$qty = Mass::hasUnit($unit) ? new Mass($scalar, $unit) : new Volume($scalar, $unit);
```
  But your point is taken, there's no way to have an object that represents an ambiguous physical quantity.

Feel free to submit a PR or else just a link to your branch; I'd be happy to take a look at what you've done and consider the concepts for inclusion.  But I can't promise I'll directly accept any significant changes to the library any time soon.

Thanks again for your interest.
