### ISSUE TITLE
Create organization "PhpUnitsOfMeasure"

### ISSUE THREAD

**Issue by h4cc** [PhpUnitsOfMeasure/php-units-of-measure#36]
How about creating a organization, that could host this library and maybe other depending sources?
Like a Symfony2 bundle i am trying myself on, or a Laravel Extension?

This could be an interesting read on that topic: http://fabien.potencier.org/article/75/about-personal-github-accounts

**Comment by h4cc** [comment]
Current state of the symfony2 bundle: https://github.com/h4cc/UnitOfMeasuresBundle

**Comment by triplepoint** [comment]
Hi Julius, thanks for your interest in this project!  Sorry it took me so long to address this issue.

I don't mind moving the triplepoint/php-units-of-measure code over to a separate enclosing GitHub organization.  This started as a personal repository largely because I didn't think anyone would have a use for it, but I can see now that there are several people finding and using this library in their work.

I do still have some pretty disruptive plans lined up for this library, to explore applying multiplication and division to generate new unit types from existing unit types.  But this can be done in a private fork and PR'ed later.

I see there's already a PhpUnitsOfMeasure organization started.  let me know how you want to handle combining these projects.

**Comment by h4cc** [comment]
Thanks for your answer. First of all, no rush needed to change anything.
I invited you to join the organization, so we can proceed further.

**Comment by triplepoint** [comment]
This was eventually done.
